"""Additional Gravitre marketplace catalog assets (MKT-AUDIT-4.5 expansion)."""
from __future__ import annotations

from app.marketplace.seed_catalog import (
    CatalogAsset,
    HUBSPOT,
    SALESFORCE,
    SLACK,
    _agent,
    _agent_step,
    _invoke,
    _rag_doc,
    _workflow,
)
from app.workflows.constants import SCHEMA_VERSION


def expansion_catalog_assets() -> list[CatalogAsset]:
    """23 depth assets extending the starter library toward the 50-asset Stage 1 minimum."""
    agents = [
        CatalogAsset(
            slug="content-strategist-agent",
            title="Content Strategist Agent",
            description="Plans editorial calendars and repurposing opportunities from performance data.",
            asset_type="ai_agent",
            category="ai_agent",
            department="Marketing",
            tags=["marketing", "content", "starter"],
            config=_agent(
                "content-strategist-agent",
                name="Content Strategist Agent",
                purpose="Turns analytics and CRM signals into a prioritized content plan.",
                role="Content Marketing",
                department="Marketing",
                persona_key="Marketing",
                systems=["hubspot", "google_analytics"],
                capabilities=["content-planning", "reporting"],
            ),
            required_connectors=[HUBSPOT],
            business_outcome="Reduce manual content planning time and improve campaign consistency.",
            use_case="Monthly editorial planning",
            estimated_hours_saved=6.0,
        ),
        CatalogAsset(
            slug="pipeline-forecast-agent",
            title="Pipeline Forecast Agent",
            description="Summarizes pipeline movement and forecast risk for revenue reviews.",
            asset_type="ai_agent",
            category="ai_agent",
            department="Sales",
            tags=["sales", "forecast", "starter"],
            config=_agent(
                "pipeline-forecast-agent",
                name="Pipeline Forecast Agent",
                purpose="Highlights forecast changes, stalled deals, and coverage gaps.",
                role="Sales Operations",
                department="Sales",
                persona_key="Sales",
                systems=["salesforce"],
                capabilities=["forecasting"],
            ),
            required_connectors=[SALESFORCE],
            business_outcome="Improve forecast accuracy and reduce manual pipeline review prep.",
            use_case="Weekly forecast call preparation",
            estimated_hours_saved=5.0,
        ),
        CatalogAsset(
            slug="renewal-risk-agent",
            title="Renewal Risk Agent",
            description="Flags renewal risk based on product usage and support signals.",
            asset_type="ai_agent",
            category="ai_agent",
            department="Customer Success",
            tags=["customer-success", "renewals", "starter"],
            config=_agent(
                "renewal-risk-agent",
                name="Renewal Risk Agent",
                purpose="Prioritizes accounts needing proactive renewal outreach.",
                role="Customer Success Manager",
                department="Customer Success",
                persona_key="CustomerSuccess",
                systems=["hubspot"],
                capabilities=["renewals", "health-scoring"],
            ),
            required_connectors=[HUBSPOT],
            business_outcome="Increase renewal predictability and reduce surprise churn.",
            use_case="Quarterly renewal planning",
            estimated_hours_saved=4.0,
        ),
        CatalogAsset(
            slug="finance-variance-agent",
            title="Finance Variance Agent",
            description="Explains budget vs actual variances for operating reviews.",
            asset_type="ai_agent",
            category="ai_agent",
            department="Finance",
            tags=["finance", "reporting", "starter"],
            config=_agent(
                "finance-variance-agent",
                name="Finance Variance Agent",
                purpose="Summarizes variance drivers for leadership reviews.",
                role="Financial Planning & Analysis",
                department="Finance",
                persona_key="Finance",
                systems=[],
                capabilities=["variance-analysis"],
            ),
            business_outcome="Accelerate monthly close commentary and leadership reporting.",
            use_case="Monthly operating review",
            estimated_hours_saved=8.0,
        ),
        CatalogAsset(
            slug="it-incident-triage-agent",
            title="IT Incident Triage Agent",
            description="Summarizes incident impact and recommended next actions for MSP teams.",
            asset_type="ai_agent",
            category="ai_agent",
            department="Operations",
            tags=["msp", "operations", "starter"],
            config=_agent(
                "it-incident-triage-agent",
                name="IT Incident Triage Agent",
                purpose="Prioritizes incidents and drafts stakeholder updates.",
                role="MSP Operations",
                department="Operations",
                persona_key="Operations",
                systems=["slack"],
                capabilities=["incident-response"],
            ),
            required_connectors=[SLACK],
            business_outcome="Reduce time-to-triage and improve incident communication quality.",
            use_case="High-severity incident response",
            estimated_hours_saved=3.0,
        ),
        CatalogAsset(
            slug="talent-pipeline-agent",
            title="Talent Pipeline Agent",
            description="Summarizes hiring funnel health and bottleneck roles.",
            asset_type="ai_agent",
            category="ai_agent",
            department="HR",
            tags=["hr", "recruiting", "starter"],
            config=_agent(
                "talent-pipeline-agent",
                name="Talent Pipeline Agent",
                purpose="Surfaces hiring bottlenecks and candidate pipeline risks.",
                role="HR Operations",
                department="HR",
                persona_key="HR",
                systems=[],
                capabilities=["recruiting-analytics"],
            ),
            business_outcome="Improve recruiting throughput with faster pipeline reviews.",
            use_case="Weekly recruiting standup",
            estimated_hours_saved=2.5,
        ),
    ]

    workflows = [
        CatalogAsset(
            slug="lead-routing-automation",
            title="Lead Routing Automation",
            description="Routes qualified inbound leads to the right owner with Slack alerts.",
            asset_type="workflow",
            category="workflow",
            department="Sales",
            tags=["workflow", "sales", "starter"],
            config=_workflow(
                "Lead Routing Automation",
                "Route qualified leads to owners and notify the team.",
                [
                    _invoke("lookup", "Lookup lead", "hubspot.contacts.search", connector="hubspot"),
                    _invoke("notify", "Notify owner", "slack.post_message", connector="slack"),
                ],
            ),
            required_connectors=[HUBSPOT, SLACK],
            business_outcome="Reduce lead response time with automated routing.",
            use_case="Inbound lead assignment",
            estimated_hours_saved=4.0,
        ),
        CatalogAsset(
            slug="campaign-performance-digest",
            title="Campaign Performance Digest",
            description="Weekly marketing performance digest for leadership.",
            asset_type="workflow",
            category="workflow",
            department="Marketing",
            tags=["workflow", "marketing", "starter"],
            config=_workflow(
                "Campaign Performance Digest",
                "Compile weekly campaign metrics and publish a digest.",
                [
                    _agent_step("analyze", "Analyze campaigns", "marketing-analyst", "Summarize channel performance."),
                    _invoke("publish", "Publish digest", "slack.post_message", connector="slack"),
                ],
            ),
            required_connectors=[SLACK],
            business_outcome="Replace manual weekly marketing reporting with an automated digest.",
            use_case="Weekly marketing review",
            estimated_hours_saved=3.0,
        ),
        CatalogAsset(
            slug="qbr-preparation-workflow",
            title="QBR Preparation Workflow",
            description="Prepares customer success QBR packets from CRM health signals.",
            asset_type="workflow",
            category="workflow",
            department="Customer Success",
            tags=["workflow", "customer-success", "starter"],
            config=_workflow(
                "QBR Preparation Workflow",
                "Generate a QBR outline and account summary.",
                [
                    _invoke("accounts", "Pull account data", "hubspot.contacts.search", connector="hubspot"),
                    _agent_step("qbr", "Draft QBR outline", "customer-success-agent", "Prepare QBR talking points."),
                ],
            ),
            required_connectors=[HUBSPOT],
            business_outcome="Standardize QBR prep and reduce manual account research.",
            use_case="Quarterly business reviews",
            estimated_hours_saved=6.0,
        ),
        CatalogAsset(
            slug="invoice-exception-review",
            title="Invoice Exception Review",
            description="Flags invoice exceptions and routes them for approval.",
            asset_type="workflow",
            category="workflow",
            department="Finance",
            tags=["workflow", "finance", "starter"],
            config=_workflow(
                "Invoice Exception Review",
                "Review invoice exceptions and notify finance approvers.",
                [
                    _agent_step("review", "Review exceptions", "cfo-agent", "Summarize invoice exceptions."),
                    _invoke("notify", "Notify approvers", "slack.post_message", connector="slack"),
                ],
            ),
            required_connectors=[SLACK],
            business_outcome="Shorten exception review cycles and improve auditability.",
            use_case="Accounts payable exception handling",
            estimated_hours_saved=5.0,
        ),
        CatalogAsset(
            slug="sla-breach-escalation",
            title="SLA Breach Escalation",
            description="Escalates tickets approaching SLA breach to on-call engineers.",
            asset_type="workflow",
            category="workflow",
            department="Operations",
            tags=["workflow", "msp", "starter"],
            config=_workflow(
                "SLA Breach Escalation",
                "Detect SLA risk and escalate to on-call.",
                [
                    _agent_step("triage", "Triage SLA risk", "it-incident-triage-agent", "Identify tickets at risk."),
                    _invoke("escalate", "Escalate on-call", "slack.post_message", connector="slack"),
                ],
            ),
            required_connectors=[SLACK],
            business_outcome="Reduce SLA misses with proactive escalation.",
            use_case="MSP ticket monitoring",
            estimated_hours_saved=4.0,
        ),
        CatalogAsset(
            slug="new-hire-onboarding-checklist",
            title="New Hire Onboarding Checklist",
            description="Guides managers through onboarding tasks with HR policy references.",
            asset_type="workflow",
            category="workflow",
            department="HR",
            tags=["workflow", "hr", "starter"],
            config=_workflow(
                "New Hire Onboarding Checklist",
                "Run a structured onboarding checklist for new hires.",
                [
                    _agent_step("guide", "Onboarding guidance", "hr-coordinator", "Generate onboarding checklist."),
                ],
            ),
            business_outcome="Improve onboarding consistency and reduce manager prep time.",
            use_case="Employee onboarding",
            estimated_hours_saved=2.0,
        ),
        CatalogAsset(
            slug="deal-desk-approval-flow",
            title="Deal Desk Approval Flow",
            description="Routes non-standard deals for approval with context summary.",
            asset_type="workflow",
            category="workflow",
            department="Revenue Operations",
            tags=["workflow", "revops", "starter"],
            config=_workflow(
                "Deal Desk Approval Flow",
                "Summarize deal exceptions and route for approval.",
                [
                    _invoke("deal", "Pull deal context", "salesforce.query", connector="salesforce"),
                    _agent_step("desk", "Deal desk summary", "revenue-operations-agent", "Summarize approval context."),
                ],
            ),
            required_connectors=[SALESFORCE],
            business_outcome="Speed up deal desk reviews with consistent context packets.",
            use_case="Non-standard deal approvals",
            estimated_hours_saved=3.5,
        ),
        CatalogAsset(
            slug="product-feedback-synthesis",
            title="Product Feedback Synthesis",
            description="Aggregates customer feedback themes for product planning.",
            asset_type="workflow",
            category="workflow",
            department="Product",
            tags=["workflow", "product", "starter"],
            config=_workflow(
                "Product Feedback Synthesis",
                "Synthesize customer feedback into product themes.",
                [
                    _agent_step("synthesize", "Synthesize feedback", "customer-success-agent", "Cluster feedback themes."),
                ],
            ),
            business_outcome="Turn scattered feedback into actionable product themes faster.",
            use_case="Product planning intake",
            estimated_hours_saved=4.0,
        ),
        CatalogAsset(
            slug="security-access-review",
            title="Security Access Review",
            description="Summarizes privileged access changes for quarterly reviews.",
            asset_type="workflow",
            category="workflow",
            department="Security",
            tags=["workflow", "security", "starter"],
            config=_workflow(
                "Security Access Review",
                "Prepare quarterly access review summary.",
                [
                    _agent_step("review", "Access review summary", "it-incident-triage-agent", "Summarize access changes."),
                ],
            ),
            business_outcome="Reduce manual effort for quarterly access certifications.",
            use_case="Quarterly access review",
            estimated_hours_saved=6.0,
        ),
    ]

    knowledge = [
        CatalogAsset(
            slug="product-marketing-knowledge",
            title="Product Marketing Knowledge Pack",
            description="Positioning, messaging, and launch playbooks.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="Marketing",
            tags=["knowledge", "marketing", "starter"],
            config={"documents": [_rag_doc("rag:positioning", "Positioning Guide"), _rag_doc("rag:launch", "Launch Playbook")]},
            business_outcome="Give agents consistent messaging context for GTM work.",
            use_case="Campaign and launch planning",
            estimated_hours_saved=2.0,
        ),
        CatalogAsset(
            slug="enterprise-sales-knowledge",
            title="Enterprise Sales Knowledge Pack",
            description="Enterprise discovery questions, security FAQ, and procurement guidance.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="Sales",
            tags=["knowledge", "sales", "starter"],
            config={"documents": [_rag_doc("rag:discovery", "Discovery Guide"), _rag_doc("rag:security-faq", "Security FAQ")]},
            business_outcome="Improve enterprise deal velocity with reusable sales intelligence.",
            use_case="Enterprise sales cycles",
            estimated_hours_saved=3.0,
        ),
        CatalogAsset(
            slug="support-operations-knowledge",
            title="Support Operations Knowledge Pack",
            description="Escalation matrix, macros, and troubleshooting runbooks.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="Customer Success",
            tags=["knowledge", "support", "starter"],
            config={"documents": [_rag_doc("rag:escalation", "Escalation Matrix"), _rag_doc("rag:macros", "Support Macros")]},
            business_outcome="Standardize support responses and reduce handle time.",
            use_case="Tier 1 support assistance",
            estimated_hours_saved=2.5,
        ),
        CatalogAsset(
            slug="finance-close-knowledge",
            title="Finance Close Knowledge Pack",
            description="Close checklist, variance commentary templates, and board metrics definitions.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="Finance",
            tags=["knowledge", "finance", "starter"],
            config={"documents": [_rag_doc("rag:close-checklist", "Close Checklist"), _rag_doc("rag:board-metrics", "Board Metrics")]},
            business_outcome="Accelerate month-end close commentary and reporting.",
            use_case="Monthly financial close",
            estimated_hours_saved=4.0,
        ),
        CatalogAsset(
            slug="compliance-operations-knowledge",
            title="Compliance Operations Knowledge Pack",
            description="Policy summaries and control evidence guidance.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="Security",
            tags=["knowledge", "compliance", "starter"],
            config={"documents": [_rag_doc("rag:controls", "Control Library"), _rag_doc("rag:evidence", "Evidence Guide")]},
            business_outcome="Speed up audit responses with centralized compliance context.",
            use_case="Audit preparation",
            estimated_hours_saved=5.0,
        ),
        CatalogAsset(
            slug="people-ops-knowledge",
            title="People Ops Knowledge Pack",
            description="Benefits FAQ, PTO policy, and manager coaching guides.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="HR",
            tags=["knowledge", "hr", "starter"],
            config={"documents": [_rag_doc("rag:benefits", "Benefits FAQ"), _rag_doc("rag:manager-coaching", "Manager Coaching Guide")]},
            business_outcome="Reduce repetitive HR policy questions with trusted references.",
            use_case="Employee and manager support",
            estimated_hours_saved=2.0,
        ),
        CatalogAsset(
            slug="revops-analytics-knowledge",
            title="RevOps Analytics Knowledge Pack",
            description="Metric definitions, funnel stages, and reporting standards.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="Revenue Operations",
            tags=["knowledge", "revops", "starter"],
            config={"documents": [_rag_doc("rag:metric-defs", "Metric Definitions"), _rag_doc("rag:funnel", "Funnel Standards")]},
            business_outcome="Align teams on RevOps definitions and reduce reporting debates.",
            use_case="Cross-functional reporting",
            estimated_hours_saved=3.0,
        ),
        CatalogAsset(
            slug="product-ops-knowledge",
            title="Product Ops Knowledge Pack",
            description="Release notes templates, roadmap rituals, and launch checklists.",
            asset_type="knowledge_pack",
            category="knowledge_pack",
            department="Product",
            tags=["knowledge", "product", "starter"],
            config={"documents": [_rag_doc("rag:release-notes", "Release Notes Template"), _rag_doc("rag:roadmap", "Roadmap Rituals")]},
            business_outcome="Standardize product operations artifacts across launches.",
            use_case="Release and roadmap planning",
            estimated_hours_saved=2.5,
        ),
    ]

    return agents + workflows + knowledge
