import type { FleetAgent, FleetEdge } from "./types"

/** Fixture fleet for Agents 4.0 prototypes — not live product data. */
export const FLEET_FIXTURE_AGENTS: FleetAgent[] = [
  {
    id: "a-lead",
    name: "Lead Enrichment Coordinator",
    role: "Sales Development",
    department: "sales",
    departmentLabel: "Sales",
    icon: "sales",
    identityColor: "violet",
    configState: "enabled",
    runtimeState: "executing",
    currentActivity: "Enriching 12 accounts",
    tasksToday: 14,
    successRate: 96,
    model: "claude-sonnet",
    lastActiveLabel: "4m ago",
    tools: ["Apollo", "Clearbit"],
    workflows: ["Revenue Enrichment"],
    connectedSystems: ["Apollo", "Clearbit"],
  },
  {
    id: "a-pipeline",
    name: "Pipeline Analyst",
    role: "Revenue Operations",
    department: "sales",
    departmentLabel: "Sales",
    icon: "analytics",
    identityColor: "cyan",
    configState: "enabled",
    runtimeState: "available",
    currentActivity: null,
    tasksToday: 8,
    successRate: 91,
    model: "gpt-4.1",
    lastActiveLabel: "22m ago",
    tools: ["HubSpot"],
    workflows: ["Pipeline Health"],
    connectedSystems: ["HubSpot"],
  },
  {
    id: "a-research",
    name: "Research Agent",
    role: "Account Research",
    department: "sales",
    departmentLabel: "Sales",
    icon: "research",
    identityColor: "blue",
    configState: "enabled",
    runtimeState: "retrieving",
    currentActivity: "Researching Northwind logistics",
    tasksToday: 6,
    successRate: 94,
    model: "claude-sonnet",
    lastActiveLabel: "1m ago",
    tools: ["Web search", "CRM"],
    workflows: ["Revenue Enrichment"],
  },
  {
    id: "a-churn",
    name: "Churn Analyst",
    role: "Customer Success",
    department: "customer_success",
    departmentLabel: "Customer Success",
    icon: "support",
    identityColor: "blue",
    configState: "enabled",
    runtimeState: "available",
    currentActivity: null,
    tasksToday: 3,
    successRate: 88,
    model: "gpt-4.1",
    lastActiveLabel: "1h ago",
    tools: ["Intercom"],
    workflows: ["Churn Risk"],
  },
  {
    id: "a-cash",
    name: "Cash Flow Analyst",
    role: "Finance",
    department: "finance",
    departmentLabel: "Finance",
    icon: "finance",
    identityColor: "green",
    configState: "enabled",
    runtimeState: "available",
    currentActivity: null,
    tasksToday: 2,
    successRate: 97,
    model: "claude-sonnet",
    lastActiveLabel: "3h ago",
    tools: ["QuickBooks"],
    workflows: ["Monthly Forecast"],
    parentAgentId: "a-pipeline",
  },
  {
    id: "a-platform",
    name: "Platform Reliability Analyst",
    role: "Infrastructure",
    department: "engineering",
    departmentLabel: "Engineering",
    icon: "reliability",
    identityColor: "teal",
    configState: "enabled",
    runtimeState: "thinking",
    currentActivity: "Reviewing error budget burn",
    tasksToday: 5,
    successRate: 99,
    model: "gpt-4.1",
    lastActiveLabel: "8m ago",
    tools: ["Datadog"],
    workflows: ["SRE Digest"],
  },
  {
    id: "a-crm",
    name: "CRM Agent",
    role: "Revenue Systems",
    department: "operations",
    departmentLabel: "Operations",
    icon: "data",
    identityColor: "cyan",
    configState: "enabled",
    runtimeState: "waiting_approval",
    currentActivity: "Waiting to update HubSpot",
    tasksToday: 9,
    successRate: 93,
    model: "claude-sonnet",
    lastActiveLabel: "Just now",
    tools: ["HubSpot"],
    workflows: ["Revenue Enrichment"],
    connectedSystems: ["HubSpot"],
  },
  {
    id: "a-visibility",
    name: "AI Visibility Analyst",
    role: "Intelligence",
    department: "marketing",
    departmentLabel: "Marketing",
    icon: "analytics",
    identityColor: "amber",
    configState: "paused",
    runtimeState: "offline",
    currentActivity: null,
    tasksToday: 0,
    successRate: 85,
    model: "gemini",
    lastActiveLabel: "2d ago",
    tools: ["Search Console"],
    workflows: [],
  },
]

/** Prototype-only edges that mirror honest production kinds (not invents for demo). */
export const FLEET_FIXTURE_EDGES: FleetEdge[] = [
  {
    id: "e-swarm-1",
    source: "a-lead",
    target: "a-research",
    kind: "delegates_to",
    label: "swarm",
    active: true,
  },
  {
    id: "e-swarm-2",
    source: "a-lead",
    target: "a-crm",
    kind: "delegates_to",
    label: "swarm",
    active: true,
  },
  {
    id: "e-conn-crm",
    source: "a-crm",
    target: "conn:hubspot",
    kind: "uses_connector",
    label: "uses",
  },
  {
    id: "e-parent",
    source: "a-pipeline",
    target: "a-cash",
    kind: "parent_of",
    label: "parent",
  },
]

export const FLEET_FIXTURE_EXTRA_NODES = [
  { id: "conn:hubspot", kind: "connector" as const, label: "HubSpot" },
]

export const FLEET_SUMMARY = {
  total: FLEET_FIXTURE_AGENTS.length,
  working: FLEET_FIXTURE_AGENTS.filter((a) =>
    ["executing", "thinking", "retrieving", "planning", "delegating"].includes(a.runtimeState),
  ).length,
  available: FLEET_FIXTURE_AGENTS.filter((a) => a.runtimeState === "available").length,
  idle: FLEET_FIXTURE_AGENTS.filter((a) => a.runtimeState === "idle" || a.runtimeState === "offline").length,
  failed: FLEET_FIXTURE_AGENTS.filter((a) => a.runtimeState === "failed").length,
  tasksToday: FLEET_FIXTURE_AGENTS.reduce((sum, a) => sum + a.tasksToday, 0),
}
