"""Catalog-wide retrieval enrichment: synthetic examples + functional tags.

Full catalog content lives in ``data/action_retrieval_enrichment_full.json``
(generated by ``scripts/generate-action-retrieval-enrichment.py``). The small
pilot map below is retained as a fallback seed for tests when the JSON is
absent (e.g. partial checkouts).

Enrichment improves HOW actions are found (embed docs + mapper boosts). It does
not change catalog_write_authority / approval / execution governance.
"""
from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

# On by default once full catalog JSON is present. Env can force off for A/B.
_ENV_FLAG = os.environ.get("GRAVITRE_ACTION_ENRICHMENT_ENABLED")
if _ENV_FLAG is not None:
    ENRICHMENT_ENABLED: bool = _ENV_FLAG.strip().lower() in {"1", "true", "yes", "on"}
else:
    ENRICHMENT_ENABLED = True

_DATA_PATH = Path(__file__).resolve().parent / "data" / "action_retrieval_enrichment_full.json"

# Historical 18-action pilot (G.5 Phase 4.2) — fallback / seed only.
ACTION_RETRIEVAL_ENRICHMENT: dict[str, dict[str, Any]] = {
    "github.issues.list": {
        "examples": [
            "search GitHub issues mentioning billing",
            "list open issues in the repo about auth",
        ],
        "tags": ["issues", "bugs", "tickets", "search", "github"],
    },
    "github.pulls.list": {
        "examples": [
            "list open pull requests awaiting review",
            "show PRs that mention billing",
        ],
        "tags": ["pulls", "prs", "code-review", "github"],
    },
    "clickup.tasks.list": {
        "examples": [
            "list my open ClickUp tasks",
            "show ClickUp tasks assigned to me",
        ],
        "tags": ["tasks", "todos", "clickup", "list"],
    },
    "clickup.spaces.list": {
        "examples": [
            "list ClickUp spaces in the workspace",
            "show available ClickUp spaces",
        ],
        "tags": ["spaces", "workspace", "clickup"],
    },
    "salesforce.contacts.search": {
        "examples": [
            "find Salesforce contacts named Sarah",
            "search Salesforce for contact Sarah Smith",
        ],
        "tags": ["contacts", "people", "crm", "salesforce", "search"],
    },
    "salesforce.leads.search": {
        "examples": [
            "search Salesforce leads in California",
            "find open Salesforce leads about pricing",
        ],
        "tags": ["leads", "prospects", "crm", "salesforce"],
    },
    "asana.tasks.create": {
        "examples": [
            "create a task in Asana called Follow up with Acme",
            "add an Asana task for the Acme follow-up",
        ],
        "tags": ["tasks", "create", "asana", "todo"],
    },
    "notion.pages.create": {
        "examples": [
            "create a Notion page titled Q3 plan",
            "make a new Notion doc for Q3 planning",
        ],
        "tags": ["pages", "docs", "notion", "create"],
    },
    "airtable.records.list": {
        "examples": [
            "find records in Airtable for Acme",
            "list Airtable rows matching Acme",
        ],
        "tags": ["records", "rows", "airtable", "search"],
    },
    "monday.items.create": {
        "examples": [
            "create a Monday.com item for onboarding",
            "add a Monday board item named onboarding",
        ],
        "tags": ["items", "boards", "monday", "create"],
    },
    "linear.issues.create": {
        "examples": [
            "create a Linear issue titled Fix login",
            "file a Linear bug: Fix login",
        ],
        "tags": ["issues", "bugs", "linear", "create"],
    },
    "zendesk.tickets.list": {
        "examples": [
            "list open Zendesk tickets",
            "show Zendesk support tickets that are open",
        ],
        "tags": ["tickets", "support", "zendesk", "list"],
    },
    "intercom.conversations.search": {
        "examples": [
            "search Intercom conversations about refund",
            "find Intercom chats mentioning refunds",
        ],
        "tags": ["conversations", "chat", "intercom", "search"],
    },
    "hubspot.contacts.search": {
        "examples": [
            "Search HubSpot for Acme contacts",
            "find HubSpot contacts at Acme",
        ],
        "tags": ["contacts", "crm", "hubspot", "search"],
    },
    "apollo.lists.create": {
        "examples": [
            "Create an Apollo contact list named MSP Prospects",
            "make a new Apollo list for outreach",
        ],
        "tags": ["lists", "labels", "apollo", "create"],
    },
    "gmail.messages.send": {
        "examples": [
            "Send an email to Stephanie about the proposal",
            "email Stephanie the proposal draft",
        ],
        "tags": ["email", "send", "gmail", "message"],
    },
    "slack.chat.postMessage": {
        "examples": [
            "post a Slack message to #ops about the deploy",
            "send Slack note to the ops channel",
        ],
        "tags": ["slack", "message", "notify", "chat"],
    },
    "hubspot.lists.create": {
        "examples": [
            "Create a HubSpot static list named MSPs",
            "make a HubSpot contact list called MSPs",
        ],
        "tags": ["lists", "segments", "hubspot", "create"],
    },
}


@lru_cache(maxsize=1)
def _load_full_catalog() -> dict[str, dict[str, Any]]:
    if not _DATA_PATH.is_file():
        return {}
    try:
        blob = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    actions = blob.get("actions") if isinstance(blob, dict) else None
    if not isinstance(actions, dict):
        return {}
    out: dict[str, dict[str, Any]] = {}
    for key, row in actions.items():
        if not isinstance(row, dict):
            continue
        out[str(key).strip().lower()] = {
            "examples": list(row.get("examples") or []),
            "tags": list(row.get("tags") or []),
        }
    return out


def enrichment_catalog() -> dict[str, dict[str, Any]]:
    """Merged full catalog (preferred) + pilot seed."""
    full = dict(_load_full_catalog())
    if not full:
        return {k: dict(v) for k, v in ACTION_RETRIEVAL_ENRICHMENT.items()}
    # Pilot overrides only fill missing keys (full catalog is source of truth).
    for k, v in ACTION_RETRIEVAL_ENRICHMENT.items():
        full.setdefault(k, dict(v))
    return full


def enrichment_coverage() -> dict[str, Any]:
    from app.connectors.action_catalog.registry import all_catalog_action_specs

    specs = list(all_catalog_action_specs())
    cat = enrichment_catalog()
    missing = [s.id for s in specs if s.id.lower() not in cat]
    present = len(specs) - len(missing)
    return {
        "catalog_action_count": len(specs),
        "enriched_action_count": present,
        "catalog_map_size": len(cat),
        "missing_count": len(missing),
        "missing_sample": missing[:20],
        "full_coverage": len(missing) == 0,
        "data_path_exists": _DATA_PATH.is_file(),
        "enrichment_enabled": ENRICHMENT_ENABLED,
    }


def enrichment_for_action(action_id: str | None) -> dict[str, Any] | None:
    if not ENRICHMENT_ENABLED:
        return None
    key = str(action_id or "").strip().lower()
    if not key:
        return None
    row = enrichment_catalog().get(key)
    return dict(row) if isinstance(row, dict) else None


def enrichment_document_suffix(action_id: str | None) -> str:
    """Embed-doc suffix: tags + up to 5 synthetic examples."""
    if not ENRICHMENT_ENABLED:
        return ""
    row = enrichment_for_action(action_id)
    if not row:
        return ""
    parts: list[str] = []
    tags = row.get("tags") or []
    if isinstance(tags, list) and tags:
        parts.append("tags: " + ", ".join(str(t) for t in tags[:8]))
    examples = row.get("examples") or []
    if isinstance(examples, list) and examples:
        parts.append("examples: " + " | ".join(str(e) for e in examples[:5]))
    return " | ".join(parts)


def clear_enrichment_cache() -> None:
    """Tests only — reload JSON after writes."""
    _load_full_catalog.cache_clear()
