"""Serve each action's real vendor endpoint to the catalog API.

The map is generated by ``scripts/build_api_reference_map.py``, which reads the
connector source rather than the action's name. It is checked in as data so the
API does not have to run an AST walk at import time, and so a change to what we
send a vendor shows up as a reviewable diff.

Provenance travels with the endpoint and is not cosmetic:

  dedicated / dedicated_multi / route_table / manual_verified
      transcribed from the implementation that issues the request.
  name_inferred
      the generic catalog_http executor derives method+path from the action's
      suffix. That IS what we send, but nothing has ever checked it against the
      vendor's published API. Serving it without the flag would let a future
      drift scan report agreement it never established.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_DATA = Path(__file__).resolve().parent / "data" / "api_reference_map.json"

# Provenance values whose endpoint was read out of the code that issues the call.
SOURCE_VERIFIED_PROVENANCE = frozenset(
    {"dedicated", "dedicated_multi", "route_table", "manual_verified"}
)


@lru_cache(maxsize=1)
def _load() -> dict[str, dict[str, Any]]:
    if not _DATA.exists():
        return {}
    try:
        payload = json.loads(_DATA.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    actions = payload.get("actions")
    return actions if isinstance(actions, dict) else {}


def api_reference_entry(tool_key: str) -> dict[str, Any] | None:
    return _load().get(tool_key)


def api_reference_for(tool_key: str) -> str | None:
    entry = _load().get(tool_key)
    return entry.get("api_reference") if entry else None


def is_source_verified(tool_key: str) -> bool:
    entry = _load().get(tool_key)
    if not entry:
        return False
    return entry.get("provenance") in SOURCE_VERIFIED_PROVENANCE
