apiVersion: v1
kind: Service
metadata:
  name: {{ include "gravitre.name" . }}-web
spec:
  selector:
    app.kubernetes.io/name: {{ include "gravitre.name" . }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
