/**
 * Authoritative provider registry — one entry per canonical provider id.
 *
 * Generated by scripts/build-provider-registry.mjs (Simple Icons → official
 * repo asset → neutral category fallback). Components resolve providers only
 * through `resolveProvider`; they never guess logos from display strings.
 */
import generated from "@/lib/provider-registry.generated.json"

export type ProviderLogoSource = "simple-icons" | "official-asset" | "fallback"

export type ProviderCategory =
  | "crm"
  | "marketing"
  | "analytics"
  | "sales"
  | "knowledge"
  | "finance"
  | "commerce"
  | "communication"
  | "email"
  | "devops"
  | "productivity"
  | "automation"
  | "support"
  | "hr"
  | "storage"
  | "data"
  | "learning"
  | "design"
  | "ai"
  | "generic"

export interface ProviderEntry {
  id: string
  /** Accessible brand name — the text equivalent of the mark. */
  name: string
  category: ProviderCategory
  aliases: string[]
  source: ProviderLogoSource
  /** Light-theme asset (brand colour). Absent for fallback entries. */
  src?: string
  /** Dark-theme asset; the white variant when the brand colour is unreadable on Carbon. */
  srcDark?: string
  hex?: string
  simpleIcon?: string
  /** Pale brand colour — sits on a small ink plate in light theme. */
  lightPlate: boolean
  /** Dark ink official asset — sits on a small light plate in dark theme. */
  darkPlate: boolean
}

export const PROVIDER_REGISTRY = (generated as { providers: Record<string, ProviderEntry> }).providers

function normalizeKey(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "")
}

const LOOKUP: Map<string, ProviderEntry> = (() => {
  const map = new Map<string, ProviderEntry>()
  for (const entry of Object.values(PROVIDER_REGISTRY)) {
    map.set(normalizeKey(entry.id), entry)
    map.set(normalizeKey(entry.name), entry)
    for (const alias of entry.aliases) map.set(normalizeKey(alias), entry)
  }
  return map
})()

/** Resolve a vendor key, catalog type or display name to its registry entry. */
export function resolveProvider(input?: string | null): ProviderEntry | undefined {
  if (!input) return undefined
  return LOOKUP.get(normalizeKey(input))
}

/** True when the provider renders an official mark (not the neutral fallback). */
export function hasProviderMark(input?: string | null): boolean {
  const entry = resolveProvider(input)
  return Boolean(entry && entry.source !== "fallback")
}
