-- Allow pipedrive connector type (OAuth CRM integration).

ALTER TABLE public.connectors DROP CONSTRAINT IF EXISTS connectors_type_check;

ALTER TABLE public.connectors
  ADD CONSTRAINT connectors_type_check
  CHECK (type IN (
    'absorb_lms',
    'acme_tools',
    'adp',
    'airtable',
    'apollo',
    'asana',
    'aws_s3',
    'bamboohr',
    'canva',
    'claude',
    'clickup',
    'clio',
    'confluence',
    'constant_contact',
    'custom',
    'email',
    'excel',
    'figma',
    'fhir',
    'freshdesk',
    'github',
    'gmail',
    'google_analytics',
    'google_calendar',
    'google_docs',
    'google_drive',
    'google_sheets',
    'gorgias',
    'gusto',
    'hootsuite',
    'hubspot',
    'intercom',
    'jira',
    'linkedin',
    'mailchimp',
    'marketo',
    'microsoft365',
    'microsoft_365',
    'microsoft_teams',
    'mixpanel',
    'monday',
    'mongodb',
    'motion',
    'n8n',
    'netsuite',
    'notion',
    'odoo',
    'outlook',
    'pagerduty',
    'pipedrive',
    'plaid',
    'postgresql',
    'quickbooks',
    'salesforce',
    'segment',
    'semrush',
    'sendgrid',
    'slack',
    'snowflake',
    'stackadapt',
    'stripe',
    'twilio',
    'webhook',
    'workday',
    'xero',
    'zapier',
    'zendesk'
  ));
