-- Additive: allow google_ads connector type (current Google Ads API, not legacy AdWords).
-- Does NOT drop any prior CHECK values (pipedrive-drop lesson).
--
-- Three-part confirmation (allowlist + registration + executors), 2026-07-27:
--   google_ads — ALLOWED_CONNECTOR_VENDORS + google_vendor_oauth + googleads.* TOOL_REGISTRY
--                + Connectors UI shipped:true (apps/web/lib/connectors.ts).

ALTER TABLE public.connectors DROP CONSTRAINT IF EXISTS connectors_type_check;

ALTER TABLE public.connectors
  ADD CONSTRAINT connectors_type_check
  CHECK (type IN (
    'absorb_lms',
    'acme_tools',
    'adp',
    'ahrefs',
    'ai_visibility_ui',
    'airtable',
    'apollo',
    'asana',
    'aws_s3',
    'bamboohr',
    'canva',
    'cisa_kev',
    'claude',
    'clay',
    'clickup',
    'clio',
    'confluence',
    'constant_contact',
    'crunchbase',
    'custom',
    'email',
    'excel',
    'fhir',
    'figma',
    'finseo',
    'fred',
    'freshdesk',
    'github',
    'gmail',
    'google_ads',
    'google_analytics',
    'google_calendar',
    'google_docs',
    'google_drive',
    'google_search_console',
    'google_sheets',
    'gorgias',
    'greenhouse',
    'gusto',
    'hootsuite',
    'hubspot',
    'intercom',
    'jira',
    'linkedin',
    'linkedin_sales_navigator',
    'mailchimp',
    'marketo',
    'microsoft365',
    'microsoft_365',
    'microsoft_teams',
    'mixpanel',
    'monday',
    'mongodb',
    'motion',
    'n8n',
    'netsuite',
    'notion',
    'nvd',
    'odoo',
    'oecd',
    'opencorporates',
    'outlook',
    'pagerduty',
    'pdl',
    'pipedrive',
    'plaid',
    'postgresql',
    'quickbooks',
    'salesforce',
    'sec_edgar',
    'segment',
    'semrush',
    'sendgrid',
    'slack',
    'snowflake',
    'stackadapt',
    'stripe',
    'twilio',
    'webhook',
    'workday',
    'world_bank',
    'xero',
    'zapier',
    'zendesk',
    'zoominfo'
  ));
